version: "1"
name: test-job
image:
  dockerfile: job.dockerfile
  context: .
services:
  redis:
    image: redis:7.0.5-alpine
    #health:
    #  cmd: redis-cli ping
  mysql:
    image: mysql:8.0.31
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db"
    health:
      cmd: mysqladmin ping
tasks: |
  sloth instance --app tipee list -o json | jq -r '.[] | select(.features.tests) | .id'
