version: "1"
name: test
image:
  dockerfile: job.dockerfile
  context: .
services:
  #redis:
    #image: redis:7.0.5-alpine
    #health:
    #  cmd: [redis-cli, ping]
  mysql:
    image: mysql:8.0.31
    env:
      MYSQL_ROOT_PASSWORD: "root"
    health:
      cmd: ["mysqladmin", "-u", "root", "-proot", "-h", "127.0.0.1", "ping"]
tasks: |
  sloth instance --app tipee list -o json | jq -r '.[] | select(.features.tests) | .id' | tail -n 1
