name: Release client
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  deploy:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Build
        env:
          CGO_ENABLED: "0"
          GO111MODULE: "on"
        run: |
          GOOS=linux  GOARCH=amd64 go build -trimpath -ldflags="-s -w -X main.version=$(basename ${{ github.ref }}) -X main.commit=${{ github.sha }}" -o bin/alfred-linux-amd64  ./client
          GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags="-s -w -X main.version=$(basename ${{ github.ref }}) -X main.commit=${{ github.sha }}" -o bin/alfred-darwin-amd64 ./client
          GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags="-s -w -X main.version=$(basename ${{ github.ref }}) -X main.commit=${{ github.sha }}" -o bin/alfred-darwin-arm64 ./client

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: bin/alfred-*
          file_glob: true
          overwrite: true
          promote: true